In [2]:
print(1,2,3,4,5,sep="*",end="$")

1*2*3*4*5$

In [6]:
l1=["apple","banana","cherry"];
print(l1)
print(l1[1])
l1=["apple","banana","cherry","orange","kiwi","melon","mango"];
print(l1);
print(l1[2:4])
l1[2]="grape";
print(l1);


['apple', 'banana', 'cherry']
banana
['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']
['cherry', 'orange']
['apple', 'banana', 'grape', 'orange', 'kiwi', 'melon', 'mango']


In [10]:
t1=("maths","physics","chemistry")
print(t1)
print(t1[0])
print(t1)

('maths', 'physics', 'chemistry')
maths
('maths', 'physics', 'chemistry')


In [15]:
d1={"harsha":90,"ravi":60,"shankar":99};
for x in d1:
    print(x)
    print(d1[x])
print(d1["harsha"])

harsha
90
ravi
60
shankar
99
90


In [57]:
import math;
print("sum of array elements is:",sum([1,2,7,3,4,5,5]))
print("len is ",len([1,2,5,3,45,]))
print("Abs of ",abs(-345))
print("round value ",round(23.5325))
print("log value is ",math.log(10))


sum of array elements is: 27
len is  5
Abs of  345
round value  24
log value is  2.302585092994046


In [23]:
def area(l,w):
    return l*w
print("Area is ",area(3,4))

Area is  12


In [27]:
import numpy as np;
a=np.array([0,1,2,3])
b=np.array([5,5,5,5])
print("matrix a ",a)
print("matrix b ",a)
print("matrix sum a+b ",a+b)
print("matrix a*b ",a*b)

matrix a  [0 1 2 3]
matrix b  [0 1 2 3]
matrix sum a+b  [5 6 7 8]
matrix a*b  [ 0  5 10 15]


In [30]:
c=np.array([[0,1,2],[3,4,5],[6,7,8]])
d=np.array([[1,2,3],[1,2,3],[1,2,3]])
e=np.array([1,2,3])
print("matrix c is \n",c)
print("matrix c is \n",d)
print("matrix c is \n",e)
print("matrix c+d is \n",c+d)
print("matrix c+e is \n",c+e)

matrix c is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
matrix c is 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
matrix c is 
 [1 2 3]
matrix c+d is 
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
matrix c+e is 
 [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [39]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix is \n",matrix)
print("second row of matrix \n",matrix[1,:])
print("second col of matrix \n",matrix[:,2])

matrix is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
second row of matrix 
 [4 5 6]
second row of matrix 
 [3 6 9]


In [44]:
print("matrix Shape: ",matrix.shape);
print("matrix size: ",matrix.size);
print("matrix dimensions: ",matrix.ndim);
print("avg of matrix: ",np.mean(matrix));
print("matrix max number: ",np.max(matrix));
print("colown with minimum numbers:",np.min(matrix,axis=1))
print("diagnol of a matrix: ",matrix.diagonal())

matrix Shape:  (3, 3)
matrix size:  9
matrix dimensions:  2
avg of matrix:  5.0
matrix max number:  9
colown with minimum numbers: [1 4 7]
diagnol of a matrix:  [1 5 9]


In [58]:
print("Flatted matrix\n",matrix.flatten())
print("Reshaping matrix\n",matrix.reshape(9,1))
print("Transposed matrix\n",matrix.T)

Flatted matrix
 [1 2 3 4 5 6 7 8 9]
Reshaping matrix
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Transposed matrix
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [56]:
mat_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_b=np.array([[1,3,1],[1,1,2],[1,3,6]])
print("matrix addition is \n",np.add(mat_a,mat_b));
print("matrix addition is \n",np.multiply(mat_a,mat_b)); 

matrix addition is 
 [[ 2  5  4]
 [ 5  6  8]
 [ 8 11 15]]
matrix addition is 
 [[ 1  6  3]
 [ 4  5 12]
 [ 7 24 54]]
